import { StyleSheet } from "@react-pdf/renderer";

export const brand = {
  ink: "#1c1917",
  body: "#44403c",
  muted: "#78716c",
  rule: "#d6d3d1",
  headerBg: "#292524",
  stripe: "#fafaf9",
  paper: "#ffffff",
  accent: "#6b5c4d",
};

export const pageBase = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 9,
    color: brand.body,
    paddingTop: 48,
    paddingBottom: 52,
    paddingHorizontal: 48,
    backgroundColor: brand.paper,
  },
  topRule: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 6,
    backgroundColor: brand.accent,
  },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 48,
    right: 48,
    borderTopWidth: 1,
    borderTopColor: brand.rule,
    paddingTop: 8,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  footerText: { fontSize: 7, color: brand.muted },
  pageNum: { fontSize: 7, color: brand.muted },
  brand: {
    fontSize: 18,
    fontFamily: "Helvetica-Bold",
    color: brand.ink,
    letterSpacing: 1,
  },
  brandSub: { fontSize: 8, color: brand.muted, marginTop: 3 },
  docTitle: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    color: brand.ink,
    textAlign: "right",
  },
  docSub: { fontSize: 8, color: brand.muted, textAlign: "right", marginTop: 2 },
  sectionTitle: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: brand.ink,
    marginTop: 14,
    marginBottom: 8,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: brand.rule,
  },
  paragraph: {
    fontSize: 9,
    color: brand.body,
    lineHeight: 1.45,
    marginBottom: 8,
  },
  tableHead: {
    flexDirection: "row",
    backgroundColor: brand.headerBg,
    paddingVertical: 6,
    paddingHorizontal: 5,
  },
  th: {
    fontSize: 7,
    color: "#fafaf9",
    fontFamily: "Helvetica-Bold",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  tr: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: brand.rule,
    paddingVertical: 6,
    paddingHorizontal: 5,
  },
  trStripe: { backgroundColor: brand.stripe },
  td: { fontSize: 8, color: brand.body },
  tdBold: { fontSize: 8, color: brand.ink, fontFamily: "Helvetica-Bold" },
  tdMono: { fontSize: 7.5, color: brand.body, fontFamily: "Courier" },
  callout: {
    marginTop: 8,
    padding: 10,
    borderLeftWidth: 3,
    borderLeftColor: brand.accent,
    backgroundColor: brand.stripe,
  },
  calloutText: { fontSize: 8.5, color: brand.body, lineHeight: 1.4 },
  bullet: {
    fontSize: 8.5,
    color: brand.body,
    marginBottom: 4,
    paddingLeft: 8,
    lineHeight: 1.35,
  },
});
